language: ruby
rvm:
 - 2.5.0
 - 2.6.0
services:
 - mysql
before_install:
  - mysql -e 'CREATE DATABASE workhorse;'
script:
 - bundle install
 - bundle exec rake test TESTOPTS='--verbose'
 - bundle exec rubocop
